### ISSUE TITLE
touch functions

### ISSUE THREAD

**Issue by freiregtr** [Xinyuan-LilyGO/T-Panel_Lite#1]
Hello, I'm trying to understand how the device's touch screen works but I can't get it to work. I can load the firmware to the device and I have no problems with anything else, I just don't understand what the touch functions are like. If you could give me a hand understanding how I should at least obtain the coordinates by serial when pressing the screen, I would appreciate it.

**Comment by freiregtr** [comment]
hi, any update?

**Comment by Llgok** [comment]
@freiregtr 
If the screen you bought has touch functionality, you can use the sample program [GFX_CST3240_Image](https://github.com/Xinyuan-LilyGO/T-Panel_Lite/tree/main/examples/GFX_CST3240_Image) to test it.

**Comment by freiregtr** [comment]
@Llgok Hi.
How am I supposed to know the version? When I bought the T panel lite screen there was only one version available, in fact in the specifications of the T panel lite it is specified that it has capacitive functions, so I would like to know if the version I have has capacitive functions because it is supposed to, right?

**Comment by Llgok** [comment]
@freiregtr 
You can use the example [IIC_Scan_2](https://github.com/Xinyuan-LilyGO/T-Panel_Lite/tree/arduino-esp32-libs_V2.0.14/examples/IIC_Scan_2) from the examples folder. If you open the serial port and can find the ID 0x5A, then it means you have the version with touch capabilities.

**Comment by freiregtr** [comment]
![image](https://github.com/user-attachments/assets/8497472f-b873-473a-bf7f-e54cfef34925) 
that is the output. Apparently I don't see any data in the table. I don't know if I should do something additional in the example or in platformio.ini since I download the project, select the example and then build it and then upload it. Then on the screen I press boot and rst and then the other way around to be able to upload the sketch.

If the output is correct, why then do they indicate that the Tpanel lite version support capacitive functions? This is indicated on the same site and when you go to buy the device it does not refer to a T-panel lite whether it comes with capacitive functions or not.

What does it mean that the device supports capacitive functions?

**Comment by Llgok** [comment]
@freiregtr 
From the image, it appears that the touch IIC address for the screen was not found, so the screen you purchased should be the non-touch version. Could you please tell me where you bought the T-Panel-Lite product?

**Comment by Llgok** [comment]
@freiregtr 
I'm very sorry, there is indeed a labeling error on the product interface. This T-Panel_Lite does not come with touch, and the one with touch is the T-Panel version. The PCB board of T-Panel_Lite supports touch screens, which means that replacing the screen of the T-Panel version with the T-Panel_Lite can also use touch.

**Comment by freiregtr** [comment]
@Llgok thanks. 
Unfortunately, we bought this device to be used with the touch functions. I wanted to make a video explaining how it works since I was thinking of making an ecosystem with your products, but unfortunately I wasted a lot of time between asking how it worked well and now knowing that it does not have a touch function, unfortunately the device is sold poorly categorized and makes one waste time in general. By the way, I bought all Lilygo products in the official store

**Comment by freiregtr** [comment]
Where am I supposed to ask for help for this problem? I bought this device on the official lilygo website and I need to know who can take care of this error

**Comment by Llgok** [comment]
@freiregtr 
Hello, you can inquire with the exclusive customer service at the store where you made your purchase for an exchange or refund.

**Comment by freiregtr** [comment]
@Llgok hello
I bought it from the official Lilygo store. Do you have any relationship with lilygo? because I'm asking through official channels, I think. I'm sorry I have to ask here, but all this is so confusing that it forces me to find out how after-sales really works.

**Comment by Llgok** [comment]
@freiregtr 
I'm truly sorry, but I'm only able to offer technical assistance. After-sales service issues cannot be addressed on GitHub. Should you have made your purchase through the "Aliexpress" mobile app, you can access after-sales support by tapping the chat icon located at the bottom left corner. Alternatively, if you bought from the official website, you can find the after-sales support by clicking on the "Help" button in the bottom right corner.
![1](https://github.com/user-attachments/assets/02e231b3-4f9d-4957-8381-702a1ee35db5)
