### ISSUE TITLE
Resolution - is it 460x460 or 480x480?

### ISSUE THREAD

**Issue by jandahl** [Xinyuan-LilyGO/T-Panel_Lite#3]
### Operating System

Irrelephant

### IDE

nvim

### Software Package Version

all

### Description

The Lilygo product page says 460x460. 

Repo says:  
> Resolution Ratio: 480x480px

### Sketch

```cpp
-
```

### Debug Message

```plain
-
```

**Comment by Llgok** [comment]
@jandahl 
The screen resolution is 480x480 pixels, but due to the casing, a portion of 20x20 pixels is obscured. Therefore, the actual visible resolution is 460x460 pixels.

**Comment by Llgok** [comment]
Closed due to inactivity for an extended period.
